theme: jekyll-theme-minimal
title: Welcome To My Online Resumsdae!
# These settings help remove GitHub-specific links and branding
github:
  is_project_page: false
  repository_url: ""
github_username: ""
